Repository danille/carator, pull requests merged in 2018-10, with the labels that each got.

#14 Car details
  app/controllers/cars_controller.rb
  app/views/cars/show.html.haml
  features/cars_garage.feature
  features/step_definitions/cars_garage_steps.rb
Labels: code review ready, enhancement

#15 Deleting cars
  .travis.yml
  app/controllers/cars_controller.rb
  app/views/cars/index.html.haml
  app/views/cars/show.html.haml
  features/cars_garage.feature
  features/step_definitions/cars_garage_steps.rb
  features/support/env.rb
  spec/rails_helper.rb
  test/test_helper.rb
Labels: enhancement, review done

#20 Extracting strings to i18n file
  .ruby-version
  Gemfile
  Gemfile.lock
  app/views/cars/_form.html.haml
  app/views/cars/index.html.haml
  app/views/cars/new.html.haml
  app/views/cars/show.html.haml
  app/views/devise/confirmations/new.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/devise/shared/_links.html.haml
  app/views/layouts/_header.html.haml
  config/locales/en.yml
  db/schema.rb
  features/step_definitions/cars_garage_steps.rb
Labels: code review ready
