Repository danille/carator, pull requests merged in 2018-09, with the labels that each got.

#1 Add car form improvements
  .travis.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/cable.js
  app/controllers/cars_controller.rb
  app/models/car.rb
  app/views/cars/_car.html.erb
  app/views/cars/_form.html.erb
  app/views/cars/new.html.erb
  config/database.yml
  db/migrate/20180829190828_change_car_production_year_type.rb
  db/migrate/20180902175322_add_trim_to_car_model.rb
  db/migrate/20180902175622_add_custom_name_to_car_model.rb
  db/schema.rb
  db/seeds.rb
  features/cars_garage.feature
  features/step_definitions/cars_garage_steps.rb
  spec/factories/cars.rb
  spec/factories/users.rb
  spec/rails_helper.rb
Labels: enhancement, help wanted

#3 Adding cars
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/cars.coffee
  app/assets/stylesheets/cars.scss
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/devise.scss
  app/assets/stylesheets/header.scss
  app/controllers/cars_controller.rb
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/helpers/cars_helper.rb
  app/helpers/home_helper.rb
  app/models/car.rb
  app/models/user.rb
  app/views/cars/_car.html.erb
  app/views/cars/_error_messages.html.erb
  app/views/cars/_form.html.erb
  app/views/cars/index.html.erb
  app/views/cars/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_rails_defaults.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20180815155238_create_cars.rb
  db/migrate/20180828135517_add_user_reference_to_car.rb
  db/migrate/20180829185600_rename_car_brand_column.rb
  db/migrate/20180829190828_change_car_production_year_type.rb
  db/migrate/20180902175322_add_trim_to_car_model.rb
  db/migrate/20180902175622_add_custom_name_to_car_model.rb
  db/schema.rb
  db/seeds.rb
  features/authentication.feature
  features/cars_garage.feature
  features/step_definitions/authentication_steps.rb
  features/step_definitions/cars_garage_steps.rb
  spec/controllers/cars_controller_spec.rb
  spec/controllers/home_controller_spec.rb
  spec/factories/cars.rb
  spec/factories/users.rb
  spec/helpers/controller_helper_spec.rb
  spec/helpers/home_helper_spec.rb
  spec/models/car_spec.rb
Labels: enhancement, review done

#10 Added app.json manifest for Heroku
  app.json
Labels: code review ready, enhancement

#11 Updated app.json manifest
  app.json
Labels: review done

#13 Dynamically change hosted app name in environment config
  app.json
  config/environments/production.rb
Labels: bug, code review ready

#4 Account confirmation via SendGrid + custom style for sign-up & reconfirmation pages
  .DS_Store
  .gitignore
  Gemfile
  Gemfile.lock
  app.json
  app/views/cars/_car.html.erb
  app/views/cars/_car.html.haml
  app/views/cars/_error_messages.html.erb
  app/views/cars/_error_messages.html.haml
  app/views/cars/_form.html.erb
  app/views/cars/_form.html.haml
  app/views/cars/index.html.erb
  app/views/cars/index.html.haml
  app/views/cars/new.html.erb
  app/views/cars/new.html.haml
  app/views/devise/confirmations/new.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.erb
  app/views/devise/sessions/new.html.haml
  app/views/devise/shared/_links.html.haml
  app/views/layouts/_header.html.erb
  app/views/layouts/_header.html.haml
  app/views/layouts/_rails_defaults.html.erb
  app/views/layouts/_rails_defaults.html.haml
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.haml
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.haml
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.haml
  config/environments/production.rb
Labels: code review ready
